config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  namespace :admin do
    root to: 'dashboards#index'
    patch 'animes/switch_public', to: 'animes#switch_public'
    resources :animes, shallow: true do
      scope module: :animes do
        scope :animes, as: :anime do
          resources :episodes, only: %w[destroy] do
            resources :tweets, only: %w[index], module: :episodes
            resources :tweets_imports, only: %w[new create], module: :episodes
            get 'more_import' => 'episodes/tweets_imports#more_import'
          end
        end
        resource :episodes, only: %w[edit update]
        resource :terms, only: %w[edit update]
      end
    end
    resources :users, except: %w[show]
    get 'login' => 'user_sessions#new'
    post 'login' => 'user_sessions#create'
    delete 'logout' => 'user_sessions#destroy'
    resources :animes_imports, only: %w[new create]
  end
  namespace :api do
    resources :animes, only: %w[index]
    resources :terms, only: %w[index]
    resources :tweets, only: %w[index]
    resources :episodes, only: %w[index] do
      collection do
        get 'info'
      end
    end
  end
  get '*path', to: 'home#index'
end

app/models/anime.rb
class Anime < ApplicationRecord
  before_validation :set_public
  has_many :anime_terms, dependent: :destroy
  has_many :terms, through: :anime_terms
  has_many :episodes, dependent: :destroy
  accepts_nested_attributes_for :terms, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :episodes, reject_if: :all_blank, allow_destroy: true
  validates :title, presence: true, uniqueness: { case_sensitive: false }
  validates :default_air_time, presence: true
  validates :public, inclusion: { in: [true, false] }

  def register_term(year, season_num)
    return if year.blank? || season_num.blank?

    # TODO: このseason_numの値は"winter"で送っても0で送っても良いようにしたい
    term = Term.find_or_create_by!(year: year.to_i, season: season_num.to_i)
    return if anime_terms.map(&:term_id).include?(term&.id)

    anime_terms.create!(term_id: term.id)
  end

  private

  def set_public
    self.public = false if public.nil?
  end
end

app/models/episode.rb
class Episode < ApplicationRecord
  before_validation :set_public
  belongs_to :anime
  has_many :tweets, dependent: :destroy
  validates :anime_id, presence: true
  validates :num, presence: true, uniqueness: { scope: :anime_id, case_sensitive: false }
  validates :broadcast_datetime, presence: true
  validates :air_time, presence: true
  validates :public, inclusion: [true, false]

  RETURN_TWEETS_NUM = 300

  def import_associate_tweets(max_tweet_id)
    return unless broadcast_datetime

    json_tweets = SearchTweetsService.call(anime.twitter_hash_tag, max_tweet_id, air_time)
    new_tweets = Tweet.convert_from_json(json_tweets, broadcast_datetime, id)
    new_tweets.each_slice(3000) do |tweets|
      Tweet.import tweets
    end
  end

  def anime_title
    anime.title
  end

  def return_tweets(over_tweet_id, progress_time_msec)
    if !over_tweet_id.blank?
      tweets.where(tweet_id: Range.new(over_tweet_id.to_i + 1, nil)).order(:tweet_id).limit(RETURN_TWEETS_NUM)
    elsif !progress_time_msec.blank?
      tweets.where(progress_time_msec: Range.new(progress_time_msec, nil)).order(:tweet_id).limit(RETURN_TWEETS_NUM)
    end
  end

  private

  def set_public
    self.public = false if public.nil?
  end
end

app/controllers/admin/animes/episodes/tweets_controller.rb
class Admin::Animes::Episodes::TweetsController < Admin::BaseController
  def index
    @search_form = if params.key?(:search)
                     SearchTweetsForm.new(search_params.to_h)
                   else
                     SearchTweetsForm.new(episode_id: params[:episode_id])
                   end
    @tweets = @search_form.search.page(params[:page])
  end

  private

  def search_params
    params.require(:search).permit(:episode_id, :begin_minutes, :begin_seconds, :end_minutes, :end_seconds)
  end
end

app/controllers/admin/animes/episodes/tweets_imports_controller.rb
class Admin::Animes::Episodes::TweetsImportsController < Admin::BaseController
  def new
    @episode = Episode.find(params[:episode_id]).decorate
    @twitter_search_limit = ConfirmTwitterLimitService.call(:search)
  end

  def create
    @episode = Episode.find(params[:episode_id]).decorate
    ImportTweetsService.call(@episode.id, params[:tweet_id])
    if !@episode.tweets.empty?
      redirect_to admin_anime_episode_tweets_path(@episode.id), success: 'ツイートを取得しました'
    else
      @twitter_search_limit = ConfirmTwitterLimitService.call(:search)
      flash.now[:danger] = 'ツイートが取得できませんでした'
      render :new
    end
  end

  def more_import
    @episode = Episode.find(params[:episode_id])
    tweets_min_id = @episode.tweets.order(:tweet_id).first.tweet_id
    ImportTweetsService.call(@episode.id, tweets_min_id - 1)
    redirect_to admin_anime_episode_tweets_path(@episode.id), success: 'ツイートを取得しました'
  end
end

app/controllers/admin/animes/episodes_controller.rb
class Admin::Animes::EpisodesController < Admin::BaseController
  def edit
    @anime = Anime.find(params[:anime_id])
  end

  def update
    @anime = Anime.find(params[:anime_id])
    if params.key?(:anime) && @anime.update(episodes_params)
      redirect_to admin_anime_path(@anime), success: 'エピソードを更新しました'
    else
      flash.now[:danger] = '更新に失敗しました'
      render :edit
    end
  end

  def destroy
    @episode = Episode.find(params[:id])
    @episode.destroy
  end

  private

  def episodes_params
    params.require(:anime).permit(episodes_attributes: %i[id num subtitle air_time broadcast_datetime public _destroy])
  end
end

app/controllers/admin/animes/import_tweets_controller.rb
class Admin::Animes::ImportTweetsController < Admin::BaseController
  def show
    @episode = Episode.find(params[:episode_id]).decorate
  end

  def import
    @episode = Episode.find(params[:episode_id])
    @episode.import_associate_tweets(params[:tweet_id]) if @episode.tweets.blank?
    redirect_to admin_animes_tweets_path(episode_id: @episode.id), success: 'ツイートを取得しました'
  end
end

app/controllers/admin/animes/terms_controller.rb
class Admin::Animes::TermsController < Admin::BaseController
  def edit
    @anime = Anime.find(params[:anime_id])
  end

  def update
    @anime = Anime.find(params[:anime_id])
    @anime.terms.destroy_all
    params.dig(:anime, :terms_attributes)&.each do |_key, value|
      next if ActiveRecord::Type::Boolean.new.cast(value[:_destroy])

      @anime.register_term(value[:year], Term.seasons[value[:season]])
    end
    redirect_to admin_anime_path(@anime), success: '放送時期を更新しました'
  end
end

app/controllers/admin/animes/tweets_controller.rb
class Admin::Animes::TweetsController < Admin::BaseController
  def index
    @search_form = if params.key?(:search)
                     SearchTweetsForm.new(search_params)
                   else
                     SearchTweetsForm.new({ episode_id: params[:episode_id] })
                   end
    @tweets = @search_form.search.page(params[:page])
  end

  private

  def search_params
    params.require(:search).permit(:episode_id, :begin_minutes, :begin_seconds, :end_minutes, :end_seconds)
  end
end

app/controllers/admin/animes/tweets_imports_controller.rb
class Admin::Animes::TweetsImportsController < Admin::BaseController
  def new
    @episode = Episode.find(params[:episode_id]).decorate
  end

  def create
    @episode = Episode.find(params[:episode_id])
    @episode.import_associate_tweets(params[:tweet_id]) if @episode.tweets.blank?
    redirect_to admin_animes_tweets_path(episode_id: @episode.id), success: 'ツイートを取得しました'
  end
end

app/controllers/admin/animes_controller.rb
class Admin::AnimesController < Admin::BaseController
  # TODO: ここはストロングパラメーターにする必要無い気がする
  def index
    @search_form = SearchAnimesForm.new(search_params)
    @animes = @search_form.search.page(params[:page]).preload(:terms)
  end

  def new
    @anime = Anime.new
  end

  def create
    @anime = Anime.new(anime_params)
    if @anime.save
      @anime.register_term(params.dig(:anime, 'year(1i)'), params.dig(:anime, :season))
      redirect_to admin_animes_path, success: 'アニメを登録しました'
    else
      flash.now[:danger] = 'アニメの登録に失敗しました'
      render :new
    end
  end

  def show
    @anime = Anime.find(params[:id])
  end

  def edit
    @anime = Anime.find(params[:id])
  end

  def update
    @anime = Anime.find(params[:id])
    @anime.update(anime_params)
    redirect_to admin_anime_path(@anime.id), success: '登録情報を更新しました'
  end

  def destroy
    @anime = Anime.find(params[:id])
    @anime.destroy
  end

  def switch_public
    @anime = Anime.find(params[:id])
    @anime.update(public: params[:public])
  end

  private

  def anime_params
    params.require(:anime).permit(:title, :public_url, :default_air_time, :first_broadcast_datetime, :twitter_account, :twitter_hash_tag, :public)
  end

  def search_params
    # ここ、なんでこんな書き方してるのか
    params[:search]&.permit(:title, :year, :season, :public)
  end
end

app/controllers/api/anime_controller.rb
class Api::AnimeController < ApplicationController
  def index
    @animes = Anime.all
    render json: @animes
  end
end

app/controllers/api/animes_controller.rb
class Api::AnimesController < ApplicationController
  def index
    term = Term.fetch_now_or_select_term(params[:year], Term.seasons[params[:season]])
    render json: term.animes
  end
end

app/controllers/api/episodes_controller.rb
class Api::EpisodesController < ApplicationController
  def index
    episodes = Anime.find(params[:id]).episodes
    render json: episodes
  end

  def info
    episode = Episode.find(params[:episode_id])
    anime = episode.anime
    render json: { episode: episode, anime: anime }
  end
end

app/views/admin/animes/episodes/_episode_fields.html.slim
tr.nested-fields
  = f.hidden_field :id
  td
    = f.number_field :num, class: 'form-control episode-num', readonly: created
  td
    = f.text_field :subtitle, class: 'form-control episode-subtitle'
  td
    = f.datetime_field :broadcast_datetime, { class: 'form-control episode-broadcast-datetime', readonly: created, value: broadcast_datetime }
  td
    = f.number_field :air_time, class: 'form-control episode-air-time', readonly: created, value: air_time
  td
    = f.select :public, { 公開: true, 非公開: false }, {}, { class: 'form-control episode-public' }
  td
    - unless created
      = link_to_remove_association '削除', f, class: 'btn btn-danger'

app/views/admin/animes/episodes/_episodes_table.html.slim
.d-flex.justify-content-between.mb-3
  h4.my-auto エピソード
  = link_to "編集", edit_admin_anime_episodes_path(anime), class: 'btn btn-outline-primary'
table.table.table-bordered
  thead
    tr
      th.text-center scope='col' width='10%' 話数
      th.text-center scope='col' width='30%' サブタイトル
      th.text-center scope='col' width='20%' 放送日
      th.text-center scope='col' width='10%' 時間(分)
      th.text-center scope='col' width='10%' 公開
      th.text-center scope='col' width='10%' ツイート
      th.text-center scope='col' width='10%'
  tbody#episodes_list
    - anime.episodes.sort_by(&:num).each do |episode|
      tr id="episode_#{episode.id}"
        td.text-center.align-middle.episode-num = episode.num
        td.text-center.align-middle.subtitle = episode.subtitle
        td.text-center.align-middle.broadcast_datetime = l episode.broadcast_datetime, format: :default
        td.text-center.align-middle.air_time = episode.air_time
        td.text-center.align-middle.public = episode.public
        // TODO: 後ほどhelper
        - if episode.tweets.empty?
          td.text-center.align-middle
            = icon 'fas', 'minus-circle', class:'red mr-1'
            = link_to '未取得', new_admin_anime_episode_tweets_import_path(episode.id)
        - else
          td.text-center.align-middle
            = icon 'fas', 'plus-circle', class:'green mr-1'
            = link_to '取得済', admin_anime_episode_tweets_path(episode.id)
        td.text-center.align-middle = link_to '削除', admin_anime_episode_path(episode.id), method: :delete, class: 'btn btn-danger',
          data: { confirm: "#{episode.num}話を削除します。\nツイートを取得してる場合、ツイートも削除されますがよろしいですか。" }, remote: true

app/views/admin/animes/episodes/destroy.js.erb
$("#episode_<%= @episode.id %>").remove();

app/views/admin/animes/episodes/edit.html.slim
h4.my-auto エピソード
.mt-4
= form_with model: @anime, url: admin_anime_episodes_path, method: :put, local: true do |f|
  = render 'admin/layouts/error_messages', object: @anime
  table.table.w-100.mx-auto.mt-4
    thead
      tr
        th.text-center width="15%" scope='col'
          | 話数
          span.red （必須）
        th.text-center width="25%" scope='col' サブタイトル
        th.text-center width="15%" scope='col'
          | 放送日
          span.red （必須）
        th.text-center width="15%" scope='col'
          | 時間
          span.red （必須）
        th.text-center width="15%" scope='col' 公開
        th width="15%"
    tbody#episodes_tbody
      .form-group
        = f.fields_for :episodes, @anime.episodes.sort_by{|i| i.num.to_i} do |episode|
          = render 'episode_fields', { f: episode, air_time: episode.object.air_time,
            created: episode.object.id, broadcast_datetime: episode.object.broadcast_datetime&.strftime('%Y-%m-%dT%H:%M') }
  .text-center
    = link_to_add_association '1行追加', f, :episodes, class: 'btn btn-default',
      render_options: {locals: { anime: @anime, air_time: 30, created: false,
      broadcast_datetime: @anime.first_broadcast_datetime&.strftime('%Y-%m-%dT%H:%M') }},
      data: { association_insertion_node: '#episodes_tbody', association_insertion_method: 'append' }
  .text-center
    = f.submit '更新', class: 'btn btn-primary mt-4'