config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  namespace :admin do
    root to: 'dashboards#index'
    patch 'animes/switch_public', to: 'animes#switch_public'
    resources :animes, shallow: true do
      scope module: :animes do
        scope :animes, as: :anime do
          resources :episodes, only: %w[destroy] do
            resources :tweets, only: %w[index], module: :episodes
            resources :tweets_imports, only: %w[new create], module: :episodes
            get 'more_import' => 'episodes/tweets_imports#more_import'
          end
        end
        resource :episodes, only: %w[edit update]
        resource :terms, only: %w[edit update]
      end
    end
    resources :users, except: %w[show]
    get 'login' => 'user_sessions#new'
    post 'login' => 'user_sessions#create'
    delete 'logout' => 'user_sessions#destroy'
    resources :animes_imports, only: %w[new create]
  end
  namespace :api do
    resources :animes, only: %w[index]
    resources :terms, only: %w[index]
    resources :tweets, only: %w[index]
    resources :episodes, only: %w[index] do
      collection do
        get 'info'
      end
    end
  end
  get '*path', to: 'home#index'
end

app/models/term.rb
class Term < ApplicationRecord
  before_validation :set_season_ja
  # TODO: set_nowメソッド実装する
  # before_validation :set_now
  has_many :anime_terms
  has_many :animes, through: :anime_terms
  validates :year, presence: true
  validates :season, presence: true, uniqueness: { scope: :year, case_sensitive: false }
  validates :season_ja, presence: true
  validates :now, inclusion: [true, false]
  # NOTE: vue.js側に値を送る際、"winter"など文字列になるので、vue.js側では統一して文字列を使用する
  enum season: { winter: 1, spring: 2, summer: 3, autumn: 4 }

  def self.fetch_now_or_select_term(year = nil, season_num = nil)
    year ||= Date.today.year
    season_num ||= (Date.today.month - 1) / 3 + 1
    Term.find_or_create_by({ year: year.to_i, season: season_num.to_i })
  end

  def self.update_all_now_attribute
    Term.update_all(now: false)
    Term.fetch_now_or_select_term.update(now: true)
  end

  private

  def set_season_ja
    case season
    when 'winter'
      season_ja = '冬'
    when 'spring'
      season_ja = '春'
    when 'summer'
      season_ja = '夏'
    when 'autumn'
      season_ja = '秋'
    end
    self.season_ja = season_ja
  end
end

app/controllers/admin/animes/terms_controller.rb
class Admin::Animes::TermsController < Admin::BaseController
  def edit
    @anime = Anime.find(params[:anime_id])
  end

  def update
    @anime = Anime.find(params[:anime_id])
    @anime.terms.destroy_all
    params.dig(:anime, :terms_attributes)&.each do |_key, value|
      next if ActiveRecord::Type::Boolean.new.cast(value[:_destroy])

      @anime.register_term(value[:year], Term.seasons[value[:season]])
    end
    redirect_to admin_anime_path(@anime), success: '放送時期を更新しました'
  end
end

app/controllers/api/terms_controller.rb
class Api::TermsController < ApplicationController
  def index
    terms = Term.all
    render json: terms
  end
end

app/views/admin/terms/_terms_table.html.slim
.d-flex.justify-content-between.mb-3
  h4.my-auto 放送時期
  = link_to "編集", admin_anime_terms_edit_path(anime_id), class: 'btn btn-outline-primary'
table.table.table-bordered
  thead
    tr
      th.text-center scope='col' 年
      th.text-center scope='col' 季節
      th.text-center scope='col' 季節(日本語)
      th.text-center scope='col' 今期
  tbody
    - @anime.terms.each do |term|
      tr
        td.text-center = term.year
        td.text-center = term.season
        td.text-center = term.season_ja
        td.text-center = term.now

app/views/admin/terms/edit_anime_terms.html.slim
h4.my-auto 放送時期
= form_with model: @form, url: admin_anime_terms_path, method: :put do |f|
  table.table.w-75.mx-auto.mt-4#term_lines
    thead
      tr
        th.text-center scope='col' 年
        th.text-center scope='col' 季節
        th.text-center scope='col' 今期
    tbody.bulk-registration-form
      = f.fields_for :terms do |ff|
        tr.item.term_line
          td
            = ff.number_field :year, class: 'form-control term-year'
          td
            = ff.select :season, {春: 2, 夏: 3, 秋: 4, 冬: 1}, {}, {class: 'form-control term-season'}
          td
            = ff.text_field :now, class: 'form-control term-now', disabled: true
          td
            = link_to '削除', '#', method: :delete, class: 'btn btn-outline-danger btn-sm mr-3'
  .text-center
    = button_to '一行追加', {}, class: 'btn btn-outline-primary btn-sm', id: 'add_term_line'
  .text-center
    = f.submit '一括登録', class: 'btn btn-primary mt-4'