config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  namespace :admin do
    root to: 'dashboards#index'
    patch 'animes/switch_public', to: 'animes#switch_public'
    resources :animes, shallow: true do
      scope module: :animes do
        scope :animes, as: :anime do
          resources :episodes, only: %w[destroy] do
            resources :tweets, only: %w[index], module: :episodes
            resources :tweets_imports, only: %w[new create], module: :episodes
            get 'more_import' => 'episodes/tweets_imports#more_import'
          end
        end
        resource :episodes, only: %w[edit update]
        resource :terms, only: %w[edit update]
      end
    end
    resources :users, except: %w[show]
    get 'login' => 'user_sessions#new'
    post 'login' => 'user_sessions#create'
    delete 'logout' => 'user_sessions#destroy'
    resources :animes_imports, only: %w[new create]
  end
  namespace :api do
    resources :animes, only: %w[index]
    resources :terms, only: %w[index]
    resources :tweets, only: %w[index]
    resources :episodes, only: %w[index] do
      collection do
        get 'info'
      end
    end
  end
  get '*path', to: 'home#index'
end

app/controllers/admin/user_sessions_controller.rb
class Admin::UserSessionsController < Admin::BaseController
  layout 'admin/layouts/login'
  skip_before_action :require_admin_login, only: %i[new create]
  skip_before_action :require_admin_role, only: %i[new create]

  def new; end

  def create
    @user = login(params[:email], params[:password])

    if @user
      redirect_back_or_to admin_root_path, success: 'ログインしました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/views/admin/user_sessions/new.html.slim
.login-box.login-box-position
  .login-logo
    h2 ログイン
  .card
    .card-body.login-card-body
      = form_with url: admin_login_path, local: true do |f|
        .form-group
          = f.label :email, 'メールアドレス'
          = f.email_field :email, class:'form-control'
        .form-group
          = f.label :password, 'パスワード'
          = f.password_field :password, class:'form-control'
        .actions
          = f.submit 'ログイン', class:'btn btn-primary'